import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const iranYekan = localFont({
  src: [
    {
      path: "./fonts/iranyekanwebregular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/iranyekanwebbold.woff",
      weight: "500",
      style: "bold",
    },
  ],
});
const rokh = localFont({
  src: "/fonts/RokhVFGX.ttf",
});

export const metadata: Metadata = {
  title: "iran Tour",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${iranYekan.className} ${rokh.className} antialiased`}>
        <main className="h-[100rem]">{children}</main>
      </body>
    </html>
  );
}
